/*
 * doom_agent_tflm.cc — TFLite Micro interpreter bridge.
 *
 * This file provides the C-linkage functions that doom_agent.c calls.
 * It must be compiled as C++ because the TFLM API is C++.
 */

#include <cstring>

#include "doom_agent.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

/* Model data — generated by xxd -i doom_agent_int8.tflite.
 * Defined in doom_agent_model.c (or linked as a const array). */
extern "C" const unsigned char doom_agent_model[];
extern "C" const unsigned int doom_agent_model_len;

/* Tensor arena — sized for peak activation memory.
 * CNN activations dominate: 6×8×32 = 1536 bytes INT8 per layer.
 * 64 KB is generous for our ~400K param model. */
static constexpr int kArenaSize = 64 * 1024;
static uint8_t tensor_arena[kArenaSize];

static tflite::MicroInterpreter* interpreter = nullptr;
static TfLiteTensor* input_visual = nullptr;
static TfLiteTensor* input_state = nullptr;
static TfLiteTensor* output_action = nullptr;

extern "C" int tflm_init(void) {
  const tflite::Model* model = tflite::GetModel(doom_agent_model);
  if (model == nullptr) {
    return -1;
  }

  /* Register only the ops our model uses. */
  static tflite::MicroMutableOpResolver<12> resolver;
  resolver.AddConv2D();
  resolver.AddDepthwiseConv2D();
  resolver.AddFullyConnected();
  resolver.AddReshape();
  resolver.AddConcatenation();
  resolver.AddLogistic(); /* sigmoid */
  resolver.AddQuantize();
  resolver.AddDequantize();
  resolver.AddTranspose();
  resolver.AddTanh();
  resolver.AddMean();

  static tflite::MicroInterpreter static_interpreter(model, resolver,
                                                     tensor_arena, kArenaSize);
  interpreter = &static_interpreter;

  if (interpreter->AllocateTensors() != kTfLiteOk) {
    return -1;
  }

  /* Bind input/output tensors.
   * Index 0 = visual (45×60×4 INT8 NHWC), Index 1 = state (20 INT8).
   * These indices must match the export order in training/export.py. */
  input_visual = interpreter->input(0);
  input_state = interpreter->input(1);
  output_action = interpreter->output(0);

  return 0;
}

extern "C" void tflm_get_state_quant(float* scale, int32_t* zero_point) {
  if (input_state != nullptr) {
    *scale = input_state->params.scale;
    *zero_point = input_state->params.zero_point;
  } else {
    /* Fallback: assume scale=1/127, zp=0 (symmetric). */
    *scale = 1.0f / 127.0f;
    *zero_point = 0;
  }
}

extern "C" uint8_t tflm_infer(
    const int8_t frame_nhwc[AGENT_FRAME_H * AGENT_FRAME_W * AGENT_FRAME_STACK],
    const int8_t state_q[20]) {
  /* Copy preprocessed data into input tensors. */
  std::memcpy(input_visual->data.int8, frame_nhwc,
              AGENT_FRAME_H * AGENT_FRAME_W * AGENT_FRAME_STACK);
  std::memcpy(input_state->data.int8, state_q, 20);

  /* Run inference. */
  if (interpreter->Invoke() != kTfLiteOk) {
    return 0;
  }

  /* Decode output: 6× INT8 sigmoid probabilities → action bitfield.
   * Dequantize each output and threshold at 0.5. */
  const float out_scale = output_action->params.scale;
  const int32_t out_zp = output_action->params.zero_point;
  uint8_t actions = 0;

  for (int i = 0; i < AGENT_NUM_ACTIONS; i++) {
    const float prob = (output_action->data.int8[i] - out_zp) * out_scale;
    if (prob > 0.5f) {
      actions |= (1u << i);
    }
  }

  return actions;
}

extern "C" void tflm_destroy(void) {
  interpreter = nullptr;
  input_visual = nullptr;
  input_state = nullptr;
  output_action = nullptr;
}
