/*
 * w_file_embedded.c — WAD I/O from a const blob linked into the binary.
 *
 * Replaces w_file_stdc.c for bare-metal targets where the WAD is
 * embedded at build time via objcopy.  Provides the same stdc_wad_file
 * symbol that doomgeneric's w_file.c expects.
 *
 * The embedded blob lives in the .wad linker section (placed in DDR
 * by the linker script).  Since the data is already in memory, we
 * set wad->mapped so the engine can access it directly without copies.
 */

#include <stdint.h>
#include <string.h>

#include "w_file.h"
#include "z_zone.h"

/* Symbols generated by objcopy from the WAD binary. */
extern const uint8_t _embedded_wad_start[];
extern const uint8_t _embedded_wad_end[];

typedef struct {
  wad_file_t wad;
} embedded_wad_file_t;

/* Forward declaration — defined at bottom. */
extern wad_file_class_t stdc_wad_file;

static wad_file_t* W_Embedded_OpenFile(char* path) {
  (void)path; /* Only one WAD — ignore the path. */

  unsigned int size = (unsigned int)(_embedded_wad_end - _embedded_wad_start);

  embedded_wad_file_t* result =
      Z_Malloc(sizeof(embedded_wad_file_t), PU_STATIC, 0);
  result->wad.file_class = &stdc_wad_file;
  result->wad.mapped = (byte*)_embedded_wad_start;
  result->wad.length = size;

  return &result->wad;
}

static void W_Embedded_CloseFile(wad_file_t* wad) { Z_Free(wad); }

static size_t W_Embedded_Read(wad_file_t* wad, unsigned int offset,
                              void* buffer, size_t buffer_len) {
  if (offset >= wad->length) return 0;
  if (offset + buffer_len > wad->length) {
    buffer_len = wad->length - offset;
  }
  memcpy(buffer, _embedded_wad_start + offset, buffer_len);
  return buffer_len;
}

wad_file_class_t stdc_wad_file = {
    W_Embedded_OpenFile,
    W_Embedded_CloseFile,
    W_Embedded_Read,
};
